### PR TITLE
Exposing additional metadata from the file

### LINKED ISSUE #26: Expose additional data from the .lss file
It would be very nice if additional data could be extracted from the XML file.

Following data comes to mind:

- Game
- Game Icon (maybe even parse the base64 data)
- Category
- Platform
- (LiveSplit) Version
- Offset

### PR DESCRIPTION
**Pull request by BrainStone**
Fixes #26

### CODE REVIEW

**Comment by TrevorBushnell** [comment]
Hi! These were pieces of information that weren't useful to us at the time of initial creation but definitely doesn't hurt to have available :)

I've got some crazy stuff in my personal and academic life that are wrapping up soon, so I will get to actually testing this and looking at your other issue by the end of the week!

**Comment by BrainStone** [comment]
Thanks for looking into it. That will allow me to finish my PB uploading tool ^^

I'll look into also adding the GameTime stuff. When I made that Issue I was just done with an hours long session 😅

**Comment by TrevorBushnell** [comment]
I am a bit of an open-source newbie so I'm not sure how things work... but is it possible for you to create a pull request that puts these changes into the dev branch on this repository? We usually put new features there and then when enough new features have been compiled to create a new version I merge dev into main. Otherwise I tested and these changes look good!

**Comment by BrainStone** [comment]
Would it work like that? If not I can rebase.

**Comment by TrevorBushnell** [comment]
Yup that's it! Merging now :)

**Pull request merged**
